/* Brown GAMMA — scripts.js */
(function () {
    'use strict';

    /* =====================================================================
       Hero slideshow
       Slides come from images/banner/. Two sources, in order:
         1. images/banner/manifest.json — auto-generated by the GitHub
            Action in .github/workflows/banner-manifest.yml whenever an
            image is added/removed. Just drop a photo in the folder & push.
         2. Fallback (no manifest, e.g. opened as a local file): probe for
            slide1.jpg, slide2.jpg, ... until three in a row are missing.
       ===================================================================== */
    var BANNER_DIR = 'images/banner/';
    var SLIDE_INTERVAL = 5000;

    function initSlideshow(files) {
        var stage = document.querySelector('.hero-slideshow');
        var dotsContainer = document.querySelector('.hero-dots');
        if (!stage || !files.length) return;

        var slides = files.map(function (file, i) {
            var el = document.createElement('div');
            el.className = 'slide' + (i === 0 ? ' active' : '');
            el.style.backgroundImage = "url('" + BANNER_DIR + encodeURIComponent(file) + "')";
            stage.appendChild(el);
            return el;
        });

        if (slides.length < 2) return;

        var dots = [];
        if (dotsContainer) {
            dots = slides.map(function (_, i) {
                var dot = document.createElement('button');
                dot.className = 'hero-dot' + (i === 0 ? ' active' : '');
                dot.setAttribute('aria-label', 'Go to slide ' + (i + 1));
                dot.addEventListener('click', function () { goTo(i); });
                dotsContainer.appendChild(dot);
                return dot;
            });
        }

        var current = 0, timer;
        function goTo(i) {
            slides[current].classList.remove('active');
            if (dots[current]) dots[current].classList.remove('active');
            current = i;
            slides[current].classList.add('active');
            if (dots[current]) dots[current].classList.add('active');
            clearTimeout(timer);
            timer = setTimeout(next, SLIDE_INTERVAL);
        }
        function next() { goTo((current + 1) % slides.length); }
        timer = setTimeout(next, SLIDE_INTERVAL);

        // Preload the second slide so the first transition is clean
        var pre = new Image();
        pre.src = BANNER_DIR + encodeURIComponent(files[1]);
    }

    function probeSlides(callback) {
        var found = [], i = 1, misses = 0;
        var exts = ['jpg', 'jpeg', 'png', 'webp'];
        function tryIndex() {
            if (misses >= 3 || i > 40) { callback(found); return; }
            var e = 0;
            function tryExt() {
                if (e >= exts.length) { misses++; i++; tryIndex(); return; }
                var img = new Image();
                var name = 'slide' + i + '.' + exts[e];
                img.onload = function () { found.push(name); misses = 0; i++; tryIndex(); };
                img.onerror = function () { e++; tryExt(); };
                img.src = BANNER_DIR + name;
            }
            tryExt();
        }
        tryIndex();
    }

    function loadSlides() {
        if (!document.querySelector('.hero-slideshow')) return;
        var done = false;
        function finish(files) { if (!done) { done = true; initSlideshow(files); } }
        fetch(BANNER_DIR + 'manifest.json', { cache: 'no-cache' })
            .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
            .then(function (list) {
                if (Array.isArray(list) && list.length) finish(list);
                else probeSlides(finish);
            })
            .catch(function () { probeSlides(finish); });
    }

    /* ===================================================================
       Navigation
       =================================================================== */
    function initNav() {
        var toggle = document.querySelector('.nav-toggle');
        var list = document.querySelector('.nav-links');
        if (toggle && list) {
            toggle.addEventListener('click', function () {
                var open = list.classList.toggle('open');
                toggle.setAttribute('aria-expanded', open);
            });
            list.querySelectorAll('a').forEach(function (a) {
                a.addEventListener('click', function () {
                    list.classList.remove('open');
                    toggle.setAttribute('aria-expanded', 'false');
                });
            });
        }

        // Scroll-spy for in-page links
        var links = Array.prototype.slice.call(document.querySelectorAll('.nav-links a[href^="#"]'));
        var pairs = links.map(function (link) {
            return { link: link, target: document.querySelector(link.getAttribute('href')) };
        }).filter(function (p) { return p.target; });
        if (pairs.length && 'IntersectionObserver' in window) {
            var spy = new IntersectionObserver(function (entries) {
                entries.forEach(function (entry) {
                    if (!entry.isIntersecting) return;
                    links.forEach(function (l) { l.classList.remove('active'); });
                    var m = pairs.find(function (p) { return p.target === entry.target; });
                    if (m) m.link.classList.add('active');
                });
            }, { rootMargin: '-40% 0px -55% 0px' });
            pairs.forEach(function (p) { spy.observe(p.target); });
        }
    }

    /* ===================================================================
       Scroll reveal
       =================================================================== */
    function initReveal() {
        var targets = document.querySelectorAll('.section-head, .about-copy, .about-figure, .discipline, .update, .calendar-frame, .join-point');
        if (!targets.length || !('IntersectionObserver' in window)) return;
        var obs = new IntersectionObserver(function (entries) {
            entries.forEach(function (entry) {
                if (entry.isIntersecting) { entry.target.classList.add('visible'); obs.unobserve(entry.target); }
            });
        }, { threshold: 0.12 });
        targets.forEach(function (el) { el.classList.add('reveal'); obs.observe(el); });
    }

    /* ===================================================================
       Team rendering (eboard-data.json)
       Data shape: { "current": [ {title, members:[...]}, ... ],
                     "past":    [ {title, members:[...]}, ... ] }
       Group:  { title, members, columns?, sort? }   columns: cards per row (default 3)
                                                     sort: "year" = order by class year
       Member: { name, classYear, role, image, color, colorLabel, bio }
       Every member renders as a card; members without a photo get an
       initials placeholder so the grid stays uniform.
       =================================================================== */
    function esc(s) {
        return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) {
            return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
        });
    }
    function initials(name) {
        return String(name || '').split(' ').map(function (p) { return p[0]; }).filter(Boolean).slice(0, 2).join('').toUpperCase() || '?';
    }
    function beltHtml(m) {
        var label = m.colorLabel || m.beltLabel;
        if (!label) return '';
        var key = m.color || m.belt || '';
        return '<span class="belt' + (key ? ' belt-' + esc(key) : '') + '">' + esc(label) + '</span>';
    }
    function nameHtml(m) {
        return esc(m.name) + (m.classYear ? '<span class="year">' + esc(m.classYear) + '</span>' : '');
    }
    function cardHtml(m) {
        var photo = m.image
            ? '<img class="person-photo" src="' + esc(m.image) + '" alt="' + esc(m.name) + '" loading="lazy">'
            : '<div class="person-photo placeholder" aria-hidden="true">' + esc(initials(m.name)) + '</div>';
        // Role and belt rows are always emitted so every card reserves the same height
        return '<article class="person">' + photo +
            '<h3>' + nameHtml(m) + '</h3>' +
            '<p class="role">' + esc(m.role || '') + '</p>' +
            (beltHtml(m) || '<span class="belt belt-none" aria-hidden="true"></span>') +
            (m.bio ? '<p class="bio">' + esc(m.bio) + '</p>' : '') +
            '</article>';
    }
    function yearKey(m) {
        // Sort key: grad students first, then class years ascending ('27, '28, ...), unknown last
        var y = String(m.classYear || '');
        if (/grad/i.test(y)) return 0;
        var n = y.match(/(\d{2,4})/);
        return n ? parseInt(n[1], 10) : 9999;
    }
    function sortMembers(members, mode) {
        if (mode !== 'year') return members;
        return members.slice().sort(function (a, b) {
            return yearKey(a) - yearKey(b) || String(a.name).localeCompare(String(b.name));
        });
    }
    function gridClass(cols) { return 'people-grid' + (cols ? ' cols-' + cols : ''); }
    function groupHtml(group) {
        var members = sortMembers(group.members || [], group.sort);
        return '<section class="team-group">' +
            '<div class="team-group-head"><h2>' + esc(group.title) + '</h2><span class="count">' + members.length + (members.length === 1 ? ' member' : ' members') + '</span></div>' +
            '<div class="' + gridClass(group.columns) + '">' + members.map(cardHtml).join('') + '</div>' +
            '</section>';
    }

    function loadTeam() {
        var full = document.querySelector('[data-team]');
        var preview = document.querySelector('[data-team-preview]');
        if (!full && !preview) return;

        fetch('eboard-data.json')
            .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
            .then(function (data) {
                if (full) {
                    var key = full.getAttribute('data-team') || 'current';
                    var groups = data[key] || [];
                    full.innerHTML = groups.map(function (g) { return groupHtml(g); }).join('') ||
                        '<p style="color:var(--muted)">Nothing here yet.</p>';
                }
                if (preview) {
                    // One centered row per group: Coaches on top, Captains below
                    preview.innerHTML = (data.current || []).filter(function (g) {
                        return /coach|captain/i.test(g.title);
                    }).map(function (g) {
                        var members = sortMembers(g.members || [], g.sort);
                        return '<div class="' + gridClass(g.columns || members.length) + '">' + members.map(cardHtml).join('') + '</div>';
                    }).join('');
                }
            })
            .catch(function (err) {
                console.error('Could not load eboard-data.json', err);
                var msg = '<p style="color:var(--muted)">Team list unavailable right now.</p>';
                if (full) full.innerHTML = msg;
                if (preview) preview.innerHTML = msg;
            });
    }

    /* =================================================================== */
    document.addEventListener('DOMContentLoaded', function () {
        loadSlides();
        initNav();
        initReveal();
        loadTeam();
        document.querySelectorAll('[data-year]').forEach(function (el) { el.textContent = new Date().getFullYear(); });
    });
})();
